# Generated by Django 5.0.6 on 2024-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="follower_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
    ]
